// <auto-generated />
using System;
using CharacterSheetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterSheetAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CharacterSheetAPI.Model.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"), 1L, 1);

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<int?>("AmbitionsCharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("CorruptionPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("SinPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterID");

                    b.HasIndex("AmbitionsCharacterID");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Ambition", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"), 1L, 1);

                    b.Property<string>("LongTermAmbition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTermAmbition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterID");

                    b.ToTable("Ambitions", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Appearance", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("BodyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistinguishingFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EyesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterID");

                    b.ToTable("Appearances", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Armor", b =>
                {
                    b.Property<int>("ArmorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArmorID"), 1L, 1);

                    b.Property<short>("ArmorPoints")
                        .HasColumnType("smallint");

                    b.Property<int>("BodyPart")
                        .HasColumnType("int");

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("ArmorID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Armors", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Characteristics", b =>
                {
                    b.Property<int>("CharacteristicsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacteristicsID"), 1L, 1);

                    b.Property<short>("BaseValue")
                        .HasColumnType("smallint");

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("CurrentValue")
                        .HasColumnType("smallint");

                    b.Property<short>("ExperienceDevelopedValue")
                        .HasColumnType("smallint");

                    b.Property<short>("TalentsDevelopedValue")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("CharacteristicsID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Characteristics", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Destiny", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("DestinyPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("LuckPoints")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterID");

                    b.ToTable("Destinies", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"), 1L, 1);

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("EquipmentID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Experience", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("Available")
                        .HasColumnType("smallint");

                    b.Property<short>("Spent")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterID");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.HeroStats", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("DeterminationPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("HeroPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterID");

                    b.ToTable("HeroStats", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Incantation", b =>
                {
                    b.Property<int>("IncantationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncantationID"), 1L, 1);

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncantationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RangeInMeters")
                        .HasColumnType("smallint");

                    b.Property<string>("SpellLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TargetsAmount")
                        .HasColumnType("smallint");

                    b.HasKey("IncantationID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Incantations", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.PsychologyEffect", b =>
                {
                    b.Property<int>("PsychologyEffectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsychologyEffectID"), 1L, 1);

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PsychologyEffectID");

                    b.HasIndex("CharacterID");

                    b.ToTable("PsychologyEffect", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"), 1L, 1);

                    b.Property<short>("BaseValue")
                        .HasColumnType("smallint");

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("CurrentValue")
                        .HasColumnType("smallint");

                    b.Property<short>("ExperienceDevelopedValue")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TalentsDevelopedValue")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("SkillID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Speed", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("RunPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("SpeedPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("WalkPoints")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterID");

                    b.ToTable("Speeds", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Talent", b =>
                {
                    b.Property<int>("TalentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentID"), 1L, 1);

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TalentID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Talents", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Team", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("LongTermAmbition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTermAmbition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterID");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Vitality", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("int");

                    b.HasKey("CharacterID");

                    b.ToTable("Vitalities", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Wealth", b =>
                {
                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("Bronze")
                        .HasColumnType("smallint");

                    b.Property<short>("Gold")
                        .HasColumnType("smallint");

                    b.Property<short>("Silver")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterID");

                    b.ToTable("Wealths", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponID"), 1L, 1);

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<short>("Damage")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("WeaponID");

                    b.HasIndex("CharacterID");

                    b.ToTable("Weapons", (string)null);
                });

            modelBuilder.Entity("CharacterSheetAPI.Model.Character", b =>
                {
                    b.HasOne("CharacterSheetAPI.Models.Ambition", "Ambitions")
                        .WithMany()
                        .HasForeignKey("AmbitionsCharacterID");

                    b.Navigation("Ambitions");
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Appearance", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Appearance")
                        .HasForeignKey("CharacterSheetAPI.Models.Appearance", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Armor", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Armor")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Characteristics", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Destiny", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Destiny")
                        .HasForeignKey("CharacterSheetAPI.Models.Destiny", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Equipment", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Equipments")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Experience", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Experience")
                        .HasForeignKey("CharacterSheetAPI.Models.Experience", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.HeroStats", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("HeroStats")
                        .HasForeignKey("CharacterSheetAPI.Models.HeroStats", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Incantation", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Incantations")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.PsychologyEffect", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("PsychologyEffects")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Skill", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Speed", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Speed")
                        .HasForeignKey("CharacterSheetAPI.Models.Speed", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Talent", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Talents")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Team", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Team")
                        .HasForeignKey("CharacterSheetAPI.Models.Team", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Vitality", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Vitality")
                        .HasForeignKey("CharacterSheetAPI.Models.Vitality", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Wealth", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithOne("Wealth")
                        .HasForeignKey("CharacterSheetAPI.Models.Wealth", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Models.Weapon", b =>
                {
                    b.HasOne("CharacterSheetAPI.Model.Character", null)
                        .WithMany("Weapons")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetAPI.Model.Character", b =>
                {
                    b.Navigation("Appearance");

                    b.Navigation("Armor");

                    b.Navigation("Characteristics");

                    b.Navigation("Destiny");

                    b.Navigation("Equipments");

                    b.Navigation("Experience");

                    b.Navigation("HeroStats");

                    b.Navigation("Incantations");

                    b.Navigation("PsychologyEffects");

                    b.Navigation("Skills");

                    b.Navigation("Speed");

                    b.Navigation("Talents");

                    b.Navigation("Team");

                    b.Navigation("Vitality");

                    b.Navigation("Wealth");

                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
